### PR TITLE
Game Select dropdown

### PR DESCRIPTION
**Pull request by silasary**
image
image

Also fixes a bug when launching the client from the Command Line.

### CODE REVIEW

**Comment by nicopop** [comment]
How does it look and work if you have way too many manual installed?
Leaving the text input to work as a search field might be a good idea.

**Comment by FuzzyGamesOn** [comment]
We should probably tweak this a bit visually, too. The spinner options when shown have an inconsistent height compared to the spinner, and they're also the same color as the spinner (and the tabs underneath). We could probably go with a bit darker background on the options to visually distinguish them.

**Comment by nicopop** [comment]
small issue with this if tracker is on thats what is loaded instead of manual client

**Comment by silasary** [comment]
I agree with both of these. Kivy does not make either easy.

**Comment by silasary** [comment]
Made them shorter, sorted alphabetically, and slightly darker.
image

**Review by nicopop — APPROVED** [review]

**Review by nicopop — APPROVED** [review]
looks good, ill look into kivy search for my idea but as is this works

**Review by FuzzyGamesOn — APPROVED** [review]

**Pull request merged**
