### PR TITLE
For some reason, we were still starting Location IDs at 501.  Let's not do that.

### PR DESCRIPTION
**Pull request by silasary**

### CODE REVIEW

**Review by nicopop — APPROVED** [review]
Oops I missed that lol

**Comment by silasary** [comment]
Yeah, I only noticed it when implementing ID skips in XIV, and it was like "50 is lower than 526"

**Review by axxroytovu — APPROVED** [review]

**Comment by FuzzyGamesOn** [comment]
We'll probably want to do another unstable release with this in it, so people can test the new ids without this bug. Good find, btw! 😃

**Review by FuzzyGamesOn — APPROVED** [review]
Yeah, this probably should've been changed a long time ago. Not sure it was ever needed 😃

**Comment by silasary** [comment]
It wasn't :D

**Pull request merged**
